/**
 * Turn gear findings into ranked recommendations.
 *
 * ## Why this exists
 *
 * The recommendations engine and the gear analyser were producing advice about
 * the same problem in two places, without knowing about each other. For the
 * reference character the engine said:
 *
 *   "Raise chaos resistance by 57% to reach the 75% cap.
 *    Reallocating the 24% of overcapped fire resistance covers part of the gap;
 *    the remaining 33% needs a new source."
 *
 * — true, and abstract. Meanwhile the gear analyser already knew the fire
 * suffix on Hypnotic Halo is provably wasted, that "of Bameth" is the best chaos
 * suffix a Ruby Ring at item level 81 can hold, that it rolls 24-27%, and that
 * three such swaps would cover the gap.
 *
 * Two systems answering the same question separately is exactly the duplication
 * this project was rebuilt to avoid. This module is the join: the engine keeps
 * ranking and costing, and the gear data supplies the specifics.
 *
 * ## What it does not do
 *
 * It never invents a swap. Every candidate comes from the spawn rules for that
 * item's own base at that item's own level, and the amount it closes is capped
 * at the real shortfall. Where no gear swap can help, no recommendation is
 * emitted and the engine's original, honest "needs a new source" stands.
 *
 * **Tier upgrades are deliberately NOT ranked here**, though the gear panel
 * lists them. A first attempt did rank them, and immediately produced
 * "improve armour on Golem Tether from tier 5 to tier 1, +208" on a character
 * whose armour is 207 — sitting directly beside the engine's own finding that
 * armour is a non-defence at that scale. Both were generated by the same tool.
 *
 * The reason is that a tier gap says a modifier COULD be bigger, not that a
 * bigger one would help. Whether armour, mana or stun threshold matters depends
 * on the build's direction, which is the judgement this project consistently
 * declines to make. Resistance shortfalls are different: the cap is a fact, and
 * being under it is measurably bad regardless of archetype.
 */

import type { EquippedItem } from '../model/slots.js'
import type { DefenseSummary } from '../defense/index.js'
import { analyzeItem, findResistanceSwaps, summarizeSwaps } from '../gear/analyze.js'
import type { ModTiers } from '../gear/tiers.js'
import type { Evidence, Recommendation } from './types.js'

/** The resistance cap, and the yardstick significance is measured against. */
const RESIST_CAP = 75

/** Cost weights, mirrored from the engine so ranking stays consistent. */
const COST_WEIGHT = { free: 1, passive: 2, gear: 4, currency: 5, unknown: 6 } as const

function score(significance: number, kind: keyof typeof COST_WEIGHT, amount: number): number {
  return significance / (COST_WEIGHT[kind] * Math.max(1, amount))
}

export interface GearRecommendationInput {
  items: EquippedItem[]
  defense: DefenseSummary
  tiers: ModTiers
}

/**
 * Concrete gear actions, ranked on the same scale as the rest of the engine.
 *
 * Returns an empty list when the affix data resolves nothing useful — a caller
 * merging these keeps its original findings, which are never wrong, only vague.
 */
export function gearRecommendations({ items, defense, tiers }: GearRecommendationInput): Recommendation[] {
  const active = items.filter((i) => i.active)
  if (!active.length) return []

  const analysed = active.map((i) => analyzeItem(i, tiers, defense))
  const swaps = findResistanceSwaps(analysed, active, tiers, defense)
  const shortfalls = summarizeSwaps(swaps, defense)

  const out: Recommendation[] = []

  // --- resistance rebalancing, per shortfall --------------------------------
  for (const shortfall of shortfalls) {
    // Only swaps that can be made on the item as it stands. A swap needing a
    // better base is a different, more expensive action and is not folded in.
    const usable = swaps
      .filter((s) => s.candidates.some((c) => c.statId === shortfall.stat && c.reachableOnThisItem))
      .slice(0, 4)
    if (!usable.length) continue

    const best = usable[0]!
    const candidate = best.candidates.find((c) => c.statId === shortfall.stat && c.reachableOnThisItem)!
    const needed = shortfall.swapsNeeded

    const evidence: Evidence[] = [
      {
        kind: 'stat',
        stat: `${shortfall.type}Resistance`,
        value: shortfall.shortfall,
        note: `${shortfall.type} resistance is ${shortfall.shortfall}% below the cap.`,
      },
      {
        kind: 'item',
        slotId: best.slotId,
        slotLabel: best.slotLabel,
        itemName: best.itemName,
        note: best.replace.reason,
      },
      {
        kind: 'breakdown',
        stat: shortfall.stat,
        source: candidate.affix ?? candidate.id,
        value: candidate.max,
        note: `"${candidate.affix ?? candidate.id}" is tier ${candidate.tier} and rolls ${candidate.min}-${candidate.max}% on this base at item level ${candidate.ilvl}.`,
      },
    ]

    out.push({
      id: `gear-swap-${shortfall.type}`,
      category: 'gear',
      action:
        `Recraft the ${best.replace.text} suffix on ${best.itemName} into "${candidate.affix ?? candidate.id}" ` +
        `(tier ${candidate.tier}, ${candidate.min}-${candidate.max}% ${shortfall.type} resistance).`,
      rationale:
        `${best.replace.reason} ` +
        (needed !== null
          ? `${needed} swap${needed === 1 ? '' : 's'} of this kind covers the ${shortfall.shortfall}% ${shortfall.type} shortfall; ${usable.length} are available.`
          : `All ${usable.length} available swaps together fall short of the ${shortfall.shortfall}% needed, so ${shortfall.type} also wants a source outside these items.`),
      impact: {
        stat: `${shortfall.type}Resistance`,
        label: `${shortfall.type[0]!.toUpperCase()}${shortfall.type.slice(1)} resistance`,
        from: RESIST_CAP - shortfall.shortfall,
        to: Math.min(RESIST_CAP, RESIST_CAP - shortfall.shortfall + candidate.closesShortfall),
        delta: candidate.closesShortfall,
        unit: 'percent',
        // Absolute points closed, against the full resistance bar — NOT against
        // the gap. Normalising by the gap made a 1-point cold fix score a
        // perfect 1.0 and outrank a swap closing 27 points of a 57-point chaos
        // hole, because it "solved" its whole (trivial) problem.
        significance: Math.min(1, candidate.closesShortfall / RESIST_CAP),
      },
      cost: {
        kind: 'gear',
        amount: needed ?? usable.length,
        currencyTier: 'low',
        detail:
          `Recrafting one suffix on ${best.itemName}` +
          (needed !== null && needed > 1 ? `, and ${needed - 1} more like it` : '') +
          '. The rest of each item is unaffected.',
      },
      tradeoff:
        `Gives up ${best.replace.text} on ${best.itemName}. That is already ${best.replace.reason.includes('doing nothing') ? 'partly wasted' : 'over cap'}, so the loss is smaller than the number suggests — but it is not zero if you later lose another source of it.`,
      evidence,
      provenance: 'ninja',
      score: score(Math.min(1, candidate.closesShortfall / RESIST_CAP), 'gear', needed ?? 1),
    })
  }

  return out.sort((a, b) => b.score - a.score)
}

/**
 * Merge gear findings into an existing set, replacing the vaguer entry where one
 * covers the same ground.
 *
 * A concrete "recraft this suffix on that item" supersedes "source 57% chaos
 * resistance from gear, a rune, or a passive" — keeping both would show the
 * reader the same problem twice and make the specific advice look optional.
 */
export function mergeGearRecommendations(
  base: Recommendation[],
  gear: Recommendation[],
): Recommendation[] {
  if (!gear.length) return base

  // A gear swap for a resistance supersedes the engine's generic under-cap entry
  // for the SAME resistance, and nothing else.
  const superseded = new Set(
    gear
      .map((g) => /^gear-swap-(\w+)$/.exec(g.id)?.[1])
      .filter((type): type is string => Boolean(type))
      .map((type) => `res-${type}-under-cap`),
  )

  return [...base.filter((r) => !superseded.has(r.id)), ...gear].sort((a, b) => b.score - a.score)
}
