/**
 * Turn gear findings into ranked recommendations.
 *
 * ## Why this exists
 *
 * The recommendations engine and the gear analyser were producing advice about
 * the same problem in two places, without knowing about each other. For the
 * reference character the engine said:
 *
 *   "Raise chaos resistance by 57% to reach the 75% cap.
 *    Reallocating the 24% of overcapped fire resistance covers part of the gap;
 *    the remaining 33% needs a new source."
 *
 * — true, and abstract. Meanwhile the gear analyser already knew the fire
 * suffix on Hypnotic Halo is provably wasted, that "of Bameth" is the best chaos
 * suffix a Ruby Ring at item level 81 can hold, that it rolls 24-27%, and that
 * three such swaps would cover the gap.
 *
 * Two systems answering the same question separately is exactly the duplication
 * this project was rebuilt to avoid. This module is the join: the engine keeps
 * ranking and costing, and the gear data supplies the specifics.
 *
 * ## What it does not do
 *
 * It never invents a swap. Every candidate comes from the spawn rules for that
 * item's own base at that item's own level, and the amount it closes is capped
 * at the real shortfall. Where no gear swap can help, no recommendation is
 * emitted and the engine's original, honest "needs a new source" stands.
 *
 * **Tier upgrades are deliberately NOT ranked here**, though the gear panel
 * lists them. A first attempt did rank them, and immediately produced
 * "improve armour on Golem Tether from tier 5 to tier 1, +208" on a character
 * whose armour is 207 — sitting directly beside the engine's own finding that
 * armour is a non-defence at that scale. Both were generated by the same tool.
 *
 * The reason is that a tier gap says a modifier COULD be bigger, not that a
 * bigger one would help. Whether armour, mana or stun threshold matters depends
 * on the build's direction, which is the judgement this project consistently
 * declines to make. Resistance shortfalls are different: the cap is a fact, and
 * being under it is measurably bad regardless of archetype.
 */

import type { EquippedItem } from '../model/slots.js'
import type { DefenseSummary } from '../defense/index.js'
import {
  AFFIX_CAPACITY,
  OCCUPIES_AFFIX_SLOT,
  analyzeItem,
  findResistanceSwaps,
  summarizeSwaps,
  type ItemAnalysis,
} from '../gear/analyze.js'
import type { ModTiers } from '../gear/tiers.js'
import type { Evidence, Recommendation } from './types.js'

/** The resistance cap, and the yardstick significance is measured against. */
const RESIST_CAP = 75

/** Cost weights, mirrored from the engine so ranking stays consistent. */
const COST_WEIGHT = { free: 1, passive: 2, gear: 4, currency: 5, unknown: 6 } as const

function score(significance: number, kind: keyof typeof COST_WEIGHT, amount: number): number {
  return significance / (COST_WEIGHT[kind] * Math.max(1, amount))
}

export interface GearRecommendationInput {
  items: EquippedItem[]
  defense: DefenseSummary
  tiers: ModTiers
}

/** One item with room left on it. */
interface OpenAffixes {
  analysis: ItemAnalysis
  prefixes: number
  suffixes: number
  total: number
}

/**
 * Affix slots that are simply empty.
 *
 * An unused slot is the one gear finding that needs no judgement about the
 * build's direction: whatever this character wants, a slot holding nothing is
 * giving nothing. That is what separates it from a tier upgrade, which this
 * module deliberately does not rank.
 *
 * ## Why an item can be skipped
 *
 * `affixCounts` counts the slot-occupying mods whose affix kind the ladder data
 * resolved. A mod it could not classify is therefore invisible to the count,
 * and subtracting from capacity would invent an open slot that is already full.
 * So an item carrying any unresolved slot-occupying mod is excluded outright and
 * reported, rather than guessed at — the count would be a floor, and a floor
 * presented as a total is exactly the failure this project avoids.
 *
 * That failure is not hypothetical. Counting only `explicit` here reported ten
 * open slots on a character whose ten items are completely full, because the
 * ten crafted and desecrated affixes holding those slots were invisible to it.
 *
 * Corrupted items are excluded because they cannot be modified, and Normal and
 * Unique items because they have no craftable affix budget.
 */
function collectOpenAffixes(analysed: ItemAnalysis[]): {
  open: OpenAffixes[]
  capacity: number
  /** Items the capacity figure covers — including those already full. */
  counted: number
  unverifiable: ItemAnalysis[]
} {
  const open: OpenAffixes[] = []
  const unverifiable: ItemAnalysis[] = []
  let capacity = 0
  let counted = 0

  for (const analysis of analysed) {
    const per = AFFIX_CAPACITY[analysis.rarity]
    if (per === undefined || analysis.corrupted || analysis.itemLevel === null) continue

    if (analysis.mods.some((m) => OCCUPIES_AFFIX_SLOT.has(m.source) && m.kind === null)) {
      unverifiable.push(analysis)
      continue
    }

    capacity += per * 2
    counted += 1
    const prefixes = Math.max(0, per - analysis.affixCounts.prefix)
    const suffixes = Math.max(0, per - analysis.affixCounts.suffix)
    if (prefixes + suffixes > 0) {
      open.push({ analysis, prefixes, suffixes, total: prefixes + suffixes })
    }
  }

  open.sort((a, b) => b.total - a.total)
  return { open, capacity, counted, unverifiable }
}

function describeSlots(prefixes: number, suffixes: number): string {
  const parts: string[] = []
  if (prefixes) parts.push(`${prefixes} prefix${prefixes === 1 ? '' : 'es'}`)
  if (suffixes) parts.push(`${suffixes} suffix${suffixes === 1 ? '' : 'es'}`)
  return parts.join(' and ')
}

/**
 * One finding for all of it, not one per item.
 *
 * On the reference character ten active items have room left. Ten separate
 * recommendations saying the same thing would bury every other finding on the
 * page, so this reports the total and leads with the emptiest item.
 */
function openAffixRule(analysed: ItemAnalysis[]): Recommendation[] {
  const { open, capacity, counted, unverifiable } = collectOpenAffixes(analysed)
  if (!open.length || capacity === 0) return []

  const slots = open.reduce((sum, o) => sum + o.total, 0)
  const worst = open[0]!
  const used = capacity - slots

  const evidence: Evidence[] = open.slice(0, 4).map(
    (o): Evidence => ({
      kind: 'item',
      slotId: o.analysis.slotId,
      slotLabel: o.analysis.slotLabel,
      itemName: o.analysis.name,
      note: `${o.analysis.name} (${o.analysis.rarity}, item level ${o.analysis.itemLevel}) has ${describeSlots(o.prefixes, o.suffixes)} unused.`,
    }),
  )

  // Suppression is never silent: an item whose modifiers could not all be
  // classified is named, so "10 open slots" is not read as "and nothing else".
  if (unverifiable.length) {
    evidence.push({
      kind: 'item',
      slotId: unverifiable[0]!.slotId,
      slotLabel: unverifiable[0]!.slotLabel,
      itemName: unverifiable[0]!.name,
      note:
        `${unverifiable.length} item${unverifiable.length === 1 ? '' : 's'} ` +
        `(${unverifiable.map((u) => u.name).join(', ')}) carry modifiers the affix data cannot classify, so their used slots ` +
        `cannot be counted and they are left out of this total entirely.`,
    })
  }

  return [
    {
      id: 'gear-open-affixes',
      category: 'gear',
      action:
        `Craft into the ${slots} empty affix slot${slots === 1 ? '' : 's'} on your gear — starting with ${worst.analysis.name}, ` +
        `which has ${describeSlots(worst.prefixes, worst.suffixes)} unused.`,
      rationale:
        `${counted} active item${counted === 1 ? '' : 's'} carry ${used} of a possible ${capacity} affixes, with ` +
        `${open.length} of them holding room. ` +
        `An empty slot grants nothing regardless of what this build is scaling, so unlike a low-tier modifier it is worth ` +
        `filling whatever direction the character takes.`,
      impact: {
        stat: 'affixSlotsUsed',
        label: 'Affix slots in use',
        from: used,
        to: capacity,
        delta: slots,
        unit: 'points',
        // Unused slots as a fraction of the budget they belong to. Bounded 0-1
        // by construction, and it falls as the gear fills rather than rewarding
        // a character for owning more items.
        significance: slots / capacity,
      },
      cost: {
        kind: 'currency',
        amount: 1,
        currencyTier: 'low',
        detail:
          `An augment per slot, on an item that keeps everything already on it. ` +
          `${slots} such slot${slots === 1 ? ' is' : 's are'} available; each is worth doing on its own.`,
      },
      tradeoff:
        'An added modifier is a rolled modifier — it cannot be chosen outright, and it spends the slot that a later, better roll would have wanted.',
      evidence,
      provenance: 'ninja',
      score: score(slots / capacity, 'currency', 1),
    },
  ]
}

/**
 * Concrete gear actions, ranked on the same scale as the rest of the engine.
 *
 * Returns an empty list when the affix data resolves nothing useful — a caller
 * merging these keeps its original findings, which are never wrong, only vague.
 */
export function gearRecommendations({ items, defense, tiers }: GearRecommendationInput): Recommendation[] {
  const active = items.filter((i) => i.active)
  if (!active.length) return []

  const analysed = active.map((i) => analyzeItem(i, tiers, defense))
  const swaps = findResistanceSwaps(analysed, active, tiers, defense)
  const shortfalls = summarizeSwaps(swaps, defense)

  const out: Recommendation[] = []

  // --- resistance rebalancing, per shortfall --------------------------------
  for (const shortfall of shortfalls) {
    // Only swaps that can be made on the item as it stands. A swap needing a
    // better base is a different, more expensive action and is not folded in.
    const usable = swaps
      .filter((s) => s.candidates.some((c) => c.statId === shortfall.stat && c.reachableOnThisItem))
      .slice(0, 4)
    if (!usable.length) continue

    const best = usable[0]!
    const candidate = best.candidates.find((c) => c.statId === shortfall.stat && c.reachableOnThisItem)!
    const needed = shortfall.swapsNeeded

    const evidence: Evidence[] = [
      {
        kind: 'stat',
        stat: `${shortfall.type}Resistance`,
        value: shortfall.shortfall,
        note: `${shortfall.type} resistance is ${shortfall.shortfall}% below the cap.`,
      },
      {
        kind: 'item',
        slotId: best.slotId,
        slotLabel: best.slotLabel,
        itemName: best.itemName,
        note: best.replace.reason,
      },
      {
        kind: 'breakdown',
        stat: shortfall.stat,
        source: candidate.affix ?? candidate.id,
        value: candidate.max,
        note: `"${candidate.affix ?? candidate.id}" is tier ${candidate.tier} and rolls ${candidate.min}-${candidate.max}% on this base at item level ${candidate.ilvl}.`,
      },
    ]

    out.push({
      id: `gear-swap-${shortfall.type}`,
      category: 'gear',
      action:
        `Recraft the ${best.replace.text} suffix on ${best.itemName} into "${candidate.affix ?? candidate.id}" ` +
        `(tier ${candidate.tier}, ${candidate.min}-${candidate.max}% ${shortfall.type} resistance).`,
      rationale:
        `${best.replace.reason} ` +
        (needed !== null
          ? `${needed} swap${needed === 1 ? '' : 's'} of this kind covers the ${shortfall.shortfall}% ${shortfall.type} shortfall; ${usable.length} are available.`
          : `All ${usable.length} available swaps together fall short of the ${shortfall.shortfall}% needed, so ${shortfall.type} also wants a source outside these items.`),
      impact: {
        stat: `${shortfall.type}Resistance`,
        label: `${shortfall.type[0]!.toUpperCase()}${shortfall.type.slice(1)} resistance`,
        from: RESIST_CAP - shortfall.shortfall,
        to: Math.min(RESIST_CAP, RESIST_CAP - shortfall.shortfall + candidate.closesShortfall),
        delta: candidate.closesShortfall,
        unit: 'percent',
        // Absolute points closed, against the full resistance bar — NOT against
        // the gap. Normalising by the gap made a 1-point cold fix score a
        // perfect 1.0 and outrank a swap closing 27 points of a 57-point chaos
        // hole, because it "solved" its whole (trivial) problem.
        significance: Math.min(1, candidate.closesShortfall / RESIST_CAP),
      },
      cost: {
        kind: 'gear',
        amount: needed ?? usable.length,
        currencyTier: 'low',
        detail:
          `Recrafting one suffix on ${best.itemName}` +
          (needed !== null && needed > 1 ? `, and ${needed - 1} more like it` : '') +
          '. The rest of each item is unaffected.',
      },
      tradeoff:
        `Gives up ${best.replace.text} on ${best.itemName}. That is already ${best.replace.reason.includes('doing nothing') ? 'partly wasted' : 'over cap'}, so the loss is smaller than the number suggests — but it is not zero if you later lose another source of it.`,
      evidence,
      provenance: 'ninja',
      score: score(Math.min(1, candidate.closesShortfall / RESIST_CAP), 'gear', needed ?? 1),
    })
  }

  // --- unused affix slots ---------------------------------------------------
  out.push(...openAffixRule(analysed))

  return out.sort((a, b) => b.score - a.score)
}

/**
 * Merge gear findings into an existing set, replacing the vaguer entry where one
 * covers the same ground.
 *
 * A concrete "recraft this suffix on that item" supersedes "source 57% chaos
 * resistance from gear, a rune, or a passive" — keeping both would show the
 * reader the same problem twice and make the specific advice look optional.
 */
export function mergeGearRecommendations(
  base: Recommendation[],
  gear: Recommendation[],
): Recommendation[] {
  if (!gear.length) return base

  // A gear swap for a resistance supersedes the engine's generic under-cap entry
  // for the SAME resistance, and nothing else.
  const superseded = new Set(
    gear
      .map((g) => /^gear-swap-(\w+)$/.exec(g.id)?.[1])
      .filter((type): type is string => Boolean(type))
      .map((type) => `res-${type}-under-cap`),
  )

  return [...base.filter((r) => !superseded.has(r.id)), ...gear].sort((a, b) => b.score - a.score)
}
